use a absolute require path
try to fix...

Warning: require(src/core/boot.php): failed to open stream: No such file or directory in /app/redaxo/index.php on line 9

Fatal error: require(): Failed opening required 'src/core/boot.php' (include_path='.:/usr/share/php') in /app/redaxo/index.php on line 9